market/urls.py
from django.urls import path
from .views import product_list, product_detail, user_profile, ProductCreateEditDelete, favorite_products,  toggle_favorite, profile

app_name = 'market'

urlpatterns = [
    path('', product_list, name = 'product_list'),
    path('user_profile/', user_profile.as_view(), name = 'user_profile'),
    path('profile/<str:username>', profile, name='profile'),
    path('product/<int:product_id>/', product_detail, name = 'product_detail'),
    path('favorites/', favorite_products, name = 'favorite_products'),
    path('products/<int:product_id>/toggle_favorite/', toggle_favorite, name = 'toggle_favorite'),
    path('product/create/', ProductCreateEditDelete.create_product, name = 'create_product'),
    path('product/edit/<int:product_id>/', ProductCreateEditDelete.edit_product, name = 'edit_product'),
    path('product/delete/<int:product_id>/', ProductCreateEditDelete.delete_product, name = 'delete_product'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('market/', include('market.urls', namespace='market')),
]

market/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings

class Version(models.Model):
    game_version = models.CharField(max_length = 200)

    def __str__(self):
        return self.game_version
    
class Type(models.Model):
    service_type = models.CharField(max_length = 200) 

    def __str__(self):
        return self.service_type

class Product(models.Model):
    service_name = models.CharField(max_length = 200)
    game_version = models.ForeignKey('Version', on_delete = models.SET_NULL, null=True)
    service_type = models.ForeignKey('Type', on_delete = models.SET_NULL, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discription = models.TextField()
    is_favorite = models.BooleanField(default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to ='products/%Y/%m/%d', blank = True)
    created_date = models.DateTimeField(auto_now_add = True)
    updated_date = models.DateTimeField(auto_now = True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def __str__(self):
        return self.service_name
       
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    location = models.CharField(max_length=100, blank=True)
    average_rating = models.DecimalField(max_digits=3, decimal_places=2, default=0)

class Rating(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='ratings')
    rating = models.IntegerField()

class Review(models.Model):
       author = models.CharField(max_length=100)
       content = models.TextField()
       product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')

class Favorite(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.product.service_name}"
    
    class Meta:
        unique_together = ('user', 'product')

market/forms.py
from django import forms
from .models import Product, Review

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['service_name', 'game_version', 'service_type', 'price', 'discription']

class ReviewForm(forms.ModelForm):
       class Meta:
           model = Review
           fields = ['content']

market/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, Favorite, Profile, Rating
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from .forms import ProductForm, ReviewForm
from django.db.models import Avg
from django.contrib.auth.decorators import login_required
from authentication.models import User


def product_list(request):
    products = Product.objects.all

    return render(request, 'market/product_list.html', {'products': products})

def product_detail(request, product_id):
       product = get_object_or_404(Product, id = product_id)
       is_favorite = Favorite.objects.filter(user=request.user, product=product).exists()

       if request.method == 'POST':
           form = ReviewForm(request.POST)

           if form.is_valid():
               review = form.save(commit = False)
               review.product = product
               review.author = request.user.username
               review.save()
               return redirect('market:product_detail', product_id = product_id)
       else:
           form = ReviewForm()
       reviews = product.reviews.all()

       return render(request, 'market/product_detail.html', {'product': product, 'form': form, 'reviews': reviews, 'is_favorite': is_favorite})

@login_required  
def favorite_products(request):
    favorites = Favorite.objects.filter(user=request.user)

    return render(request, 'market/favorite_products.html', {'favorites': favorites})

@login_required  
def toggle_favorite(request, product_id):
    product = Product.objects.get(id=product_id)
    favorite, created = Favorite.objects.get_or_create(user=request.user, product=product)

    if not created:
        favorite.delete()

    return redirect('market:product_detail', product_id=product_id)

class user_profile(LoginRequiredMixin, TemplateView):
       template_name = 'market/user_profile.html'

def profile(request, username):
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user)
    products = Product.objects.filter(user=user)
    average_rating = profile.average_rating
        
    if request.method == 'POST':
        rating_value = request.POST.get('rating')
        rating = Rating(user=user, rating=rating_value)
        rating.save()

    return render(request, 'market/profile.html', {'profile': profile,  'products': products, 'average_rating': average_rating})

class ProductCreateEditDelete:
    @login_required
    def create_product(request):
        if request.method == 'POST':
            form = ProductForm(request.POST)
            if form.is_valid():
                product = form.save(commit=False)
                product.user = request.user
                product.save()
                return redirect('market:product_list')
        else:
            form = ProductForm()
        return render(request, 'market/create_product.html', {'form': form})

    @login_required
    def delete_product(request, product_id):
        product = get_object_or_404(Product, id=product_id)
        if product.user == request.user:
            product.delete()
        return redirect('market:product_list')

    @login_required
    def edit_product(request, product_id):
        product = get_object_or_404(Product, id=product_id)
        if request.method == 'POST':
            form = ProductForm(request.POST, instance=product)
            if form.is_valid():
                form.save()
                return redirect('market:product_list')
        else:
            form = ProductForm(instance=product, initial={'service_name': product.service_name, 'game_version': product.game_version, 'service_type': product.service_type, 'price': product.price, 'description': product.description})
        return render(request, 'market/edit_product.html', {'form': form})

'''
class ProductCreateEditDelete(LoginRequiredMixin, View):
    form_class = ProductForm
    template_create = 'market/create_product.html'
    template_edit = 'market/edit_product.html'
    template_delete = 'market/delete_product.html'
    success_url = 'market:product_list'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_create, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user
            product.save()
            return redirect(self.success_url)
        return render(request, self.template_create, {'form': form})

    def delete(self, request, product_id):
        product = get_object_or_404(Product, id = product_id)
        if product.user == request.user:
            product.delete()
        return redirect(self.success_url)

    def put(self, request, product_id):
        product = get_object_or_404(Product, id = product_id)
        form = self.form_class(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        return render(request, self.template_edit, {'form': form})
'''

'''       
@login_required
def create_product(request):
       if request.method == 'POST':
           form = ProductForm(request.POST)
           if form.is_valid():
               product = form.save(commit=False)
               product.user = request.user
               product.save()
               return redirect('market:product_list')
       else:
           form = ProductForm()
       return render(request, 'market/create_product.html', {'form': form})

@login_required
def delete_product(request, product_id):
       product = get_object_or_404(Product, id = product_id)
       if product.user == request.user:
           product.delete()
       return redirect('market:product_list')

@login_required
def edit_product(request, product_id):
    product = get_object_or_404(Product, id = product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance = product)
        if form.is_valid():
            form.save()
            return redirect('market:product_list')
    else:
        form = ProductForm(instance = product, initial = {'service_name': product.service_name, 'game_version': product.game_version, 'service_type': product.service_type, 'price': product.price, 'discription': product.discription})
    return render(request, 'market/edit_product.html', {'form': form})
'''

'''
class ProductCreateEditDelete(LoginRequiredMixin, View):
    template_create = 'market/create_product.html'
    template_edit = 'market/edit_product.html'
    success_url = 'market:product_list'

    def post(self, request, product_id = None):
        if product_id is None:
            form = ProductForm(request.POST)
        else:
            product = get_object_or_404(Product, id = product_id)
            form = ProductForm(request.POST, instance = product)

        if form.is_valid():
            if product_id is None:
                product = form.save(commit=False)
                product.user = request.user
                product.save()
            else:
                form.save()
            return redirect(self.success_url)
        return render(request, self.template_create, {'form': form})

    def get(self, request, product_id = None):
        if product_id is None:
            form = ProductForm(instance = product)
        else:
            product = get_object_or_404(Product, id = product_id)
            form = ProductForm(instance=product)
        return render(request, self.template_edit, {'form': form})

    def delete(self, request, product_id):
        product = get_object_or_404(Product, id = product_id)
        if product.user == request.user:
            product.delete()
        return redirect(self.success_url)
'''

market/templates/market/base.html
<html>
<head>
    <title>Маркетплейс объявлений</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
        }

        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #ffffff;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        .form-group {
            margin-bottom: 20px;
        }

        .form-group label {
            display: block;
            margin-bottom: 5px;
            color: #333333;
        }

        .form-group input[type="text"],
        .form-group textarea {
            width: 100%;
            padding: 10px;
            border: 1px solid #cccccc;
            border-radius: 3px;
            font-size: 16px;
        }

        .form-group textarea {
            height: 120px;
        }

        .form-group button {
            padding: 10px 20px;
            background-color: #337ab7;
            color: #ffffff;
            border: none;
            border-radius: 3px;
            font-size: 16px;
            cursor: pointer;
        }

        .form-group button:hover {
            background-color: #286090;
        }
    </style>
</head>
<body>
      <div class="container">
        <div class="auth-buttons">
            <a href="/auth/register">Регистрация</a>
            <a href="/auth/login">Авторизация</a>
            <a href="/auth/logout">Выход</a>
            <a href="/market/user_profile">Профиль</a>
            <a href="/market/favorites">Избранное</a>
            <a href="/market">GGT</a>
        </div>
    <div class="container">
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
    </div>
</body>
</html>

market/templates/market/create_product.html
{% extends 'market/base.html' %}

{% block content %}
    <h1>Создать продукт</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать</button>
        <a href="{% url 'market:product_list' %}">Отмена</a>
    </form>
{% endblock %}

market/templates/market/delete_product.html
{% extends 'market/base.html' %}

{% block content %}
    <h1>Удалить продукт</h1>
    <p>Вы уверены, что хотите удалить продукт "{{ product.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Удалить</button>
        <a href="{% url 'market:product_list' %}">Отмена</a>
    </form>
{% endblock %}

market/templates/market/edit_product.html
{% extends 'market/base.html' %}

{% block content %}
    <h1>Редактировать продукт</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
        <a href="{% url 'market:product_list' %}">Отмена</a>
    </form>
{% endblock %}

market/templates/market/favorite_products.html
{% extends 'market/base.html' %}

{% block content %}
<h1>Избранные объявления</h1>
{% if favorites %}
    <ul>
        {% for favorite in favorites %}
            <li><a href="{% url "market:product_detail" favorite.product.id %}">{{ favorite.product.service_name }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>Ваш список избранных объявлений пуст.</p>
{% endif %}
{% endblock %}

market/templates/market/product_detail.html
{% extends 'market/base.html' %}

{% block content %}
    <div class="product">
          {% if is_favorite %}
              <form action="{% url 'market:toggle_favorite' product.id%}" method="POST">
                {% csrf_token %}
                <button type="submit">Удалить из избранного</button>
                </form>
          {% else %}
              <form action="{% url 'market:toggle_favorite' product.id%}" method="POST">
                {% csrf_token %}
                <button type="submit">Добавить в избранное</button>
                </form>
          {% endif %}
        <h1>{{ product.service_name }}</h1>
        <p>Продавец: <a href="{% url 'market:profile' product.user.username%}">{{ product.user.username }}</a></p>
        <p>Версия: {{ product.game_version}}</p>
        <p>Тип услуги: {{ product.service_type}}</p>
        <p>Цена в золоте: {{ product.price}}</p>
        <p>Описание: {{ product.discription}}</p>
        {% if product.user == user %}
                    <form action="{% url 'market:edit_product' product.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit">Редактировать</button>
                    </form>
        {% endif %}
        {% if product.user == user %}
                    <form action="{% url 'market:delete_product' product.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit">Удалить</button>
                    </form>
        {% endif %}
        <h2>Оставить отзыв</h2>
        <form method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Оставить отзыв</button>
        </form>
   
        <h2>Отзывы</h2>
        {% for review in reviews %}
          <div>
            <p><strong>{{ review.author }}</strong></p>
            <p>{{ review.content }}</p>
          </div>
        {% endfor %}
    </div>
{% endblock %}

market/templates/market/product_list.html
{% extends 'market/base.html' %}


{% block content %}
<a href="{% url 'market:create_product' %}"><button type="submit">Разместить объявление</button></a>
</form>
    {% for product in products %}
        <div class="product">
            <h1><a href="{% url "market:product_detail" product.id %}">{{ product.service_name }}</a></h1>
            <p>Описание: {{ product.discription}}</p>
            {% if product.user == user %}
                    <form action="{% url 'market:edit_product' product.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit">Редактировать</button>
                    </form>
            {% endif %}
            {% if product.user == user %}
                    <form action="{% url 'market:delete_product' product.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit">Удалить</button>
                    </form>
            {% endif %}
        </div>
    {% endfor %}
{% endblock %}

market/templates/market/profile.html
{% extends 'market/base.html' %}


{% block content %}
<h2>{{ profile.user.username }}</h2>

<h3>Размещенные объявления:</h3>
{% for product in products %}
<a href="{% url "market:product_detail" product.id %}">{{ product.service_name }}</a>
{% empty %}
    <p>Пользователь еще не разместил объявлений.</p>
{% endfor %}
<h3>Средняя оценка: {{ average_rating }}</h3>
<h3>Оценить пользователя:</h3>
<form method="POST" action="{% url 'market:profile' profile.user.username %}">
  {% csrf_token %}
  <select name="rating">
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>
  </select>
  <button type="submit">Оценить</button>
</form>
{% endblock %}

market/templates/market/user_profile.html
{% extends 'market/base.html' %}

{% block content %}
      <h1>Личный профиль</h1>
      <p>Имя пользователья: {{ user.username }}</p>
      <p>Номер телефона: {{ user.phone_number }}</p>
      <p>Адрес электронной почты: {{ user.email_address }}</p>
{% endblock %}